// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbCategoriaProductos
    {
        public int cpr_Id { get; set; }
        public int cpr_Categoria { get; set; }
        public int cpr_Producto { get; set; }
        public int? cpr_UsuCrea { get; set; }
        public DateTime? cpr_FechaCrea { get; set; }
        public int? cpr_usuModi { get; set; }
        public DateTime? cpr_FechaModi { get; set; }

        public virtual tbCategorias cpr_CategoriaNavigation { get; set; }
        public virtual tbProductos cpr_ProductoNavigation { get; set; }
    }
}