// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbProductos
    {
        public tbProductos()
        {
            tbCategoriaProductos = new HashSet<tbCategoriaProductos>();
            tbInventario = new HashSet<tbInventario>();
            tbVentasDetalle = new HashSet<tbVentasDetalle>();
        }

        public int pro_Id { get; set; }
        public string pro_Codigo { get; set; }
        public string pro_Nombre { get; set; }
        public string pro_StockInicial { get; set; }
        public decimal pro_Precio { get; set; }
        public int? pro_Proveedor { get; set; }
        public int? pro_usuCrea { get; set; }
        public DateTime? pro_FechaCrea { get; set; }
        public int? pro_UsuModi { get; set; }
        public DateTime? pro_FechaModi { get; set; }
        public bool? pro_Estado { get; set; }

        public virtual tbProveedores pro_ProveedorNavigation { get; set; }
        public virtual ICollection<tbCategoriaProductos> tbCategoriaProductos { get; set; }
        public virtual ICollection<tbInventario> tbInventario { get; set; }
        public virtual ICollection<tbVentasDetalle> tbVentasDetalle { get; set; }
    }
}