// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Maquillaje.Entities.Entities
{
    public partial class tbVentasDetalle
    {
        public int VD_Id { get; set; }
        public int VD_VentaId { get; set; }
        public int VD_Producto { get; set; }
        public decimal VD_Precio { get; set; }
        public int VD_Cantidad { get; set; }
        public int? VD_UsuCrea { get; set; }
        public DateTime? VD_FechaCrea { get; set; }
        public int? VD_UsuModi { get; set; }
        public DateTime? VD_FechaModi { get; set; }
        public bool? VD_Estado { get; set; }

        public virtual tbProductos VD_ProductoNavigation { get; set; }
        public virtual tbVentas VD_Venta { get; set; }
    }
}